### ISSUE TITLE
Pls add RU Filters

### ISSUE THREAD

**Issue by PROTanki** [PavelMaca/WoT-BattleMessenger#8]
".*ху.*й",
		".*хy.*",
		"бля",
		"выеб.*",
		"пид.*р",
		"мудил.*",
		"мудак.*",
		"пох",
		"hui",
		"huj",
		"pid.*r",
		"mudak",
		"suka.*",
		"шлюх.*",
		"ебал.*",
		"отсоси.*",
		".*nahui",
		"педик",
		"йопт.*",
		"млять",
		"пля",
		"плять",
		"чмо",
		"хер",
		"chmo",
		"blja",
		"bljad",
		".*ебу",
		"ебись",
		"вы.*б.*",
		"мудо.*",
		"отъеб.*",
		"bliad",
		"сучар.*",
		"хуль",
		"pox",
		"poh",
		"pohui",
		"pohuj",
		"nahuj",
		"пизд",
		"долб.*б",
		"ебаны.*",
		".*баный",
		"хуесос",
		"херня",
		"xuy",
		"ебаная",
		"ёбаная",
		"неебу",
		"ебитесь",
		"охуел",
		"пистец",
		"мля",
		"педики",
		"чмошник",
		"чмошниц",
		"мляя",
		"пляя",
		"херов",
		"ипёт",
		"ниипёт",
		"епёт",
		"мудень",
		"хня",
		"ибаццо",
		"ипаццо",
		"ибацца",
		"нахуй",
		"ипацца",
		"ebatsya",
		"ebatsa",
		"ebaniy",
		"ebanie",
		"ebanut",
		"pedik",
		"xuem",
		"xуem",
		"xujom",
		"huem",
		"hujom",
		"hernya",
		"xernya",
		"нах",
		"nahooi",
		"пнх",
		"zaebis",
		"ёп",
		"huli",
		"епет",
		"пздец",
		"пздц",
		"sukin",
		"ipalo",
		"ept",
		"хйу",
		"йух",
		"йобан",
		"hujnya",
		"дрочи",
		"епт",
		"naxer",
		"dalbaeb",
		"dalboeb",
		"dolbaeb",
		"dolboeb",
		"ebal",
		"иннах",
		"ebat",
		"xuy",
		"xuy",
		"йопан",
		"mudil",
		"дроч.*",
		"xuj",
		"mudlo",
		"xuj",
		"покуй",
		"похую",
		"заеб.*",
		"ебан",
		"хуя",
		"хуя",
		"бляг",
		"похуй",
		"хууй",
		"hernja",
		"herovo",
		"herova",
		"herovaja",
		"herovie",
		"nahooy",
		"nahooj",
		"педиг",
		"блеать",
		"блиать",
		"блеадь",
		"блиадь",
		"прием",
		".*маму",
		".*мама",
		".*папу",
		".*папа"

**Comment by pavelmaca** [comment]
Custom filters in default configuration should remain simple.
